require('dotenv').config({ path: '.env.local' });
const oracledb = require('oracledb');
const path = require('path');

// Initialize Thin Mode
try {
    oracledb.initOracleClient({ configDir: path.resolve(process.cwd(), 'oracle_wallet') });
} catch (err) { }

async function recreateWebsiteTables() {
    const adminConfig = {
        user: 'ADMIN',
        password: 'Utpal@1234567', // Your working Admin password
        connectString: 'm2_high'
    };

    let connection;
    try {
        console.log('🔌 Connecting as ADMIN to build UTPAL website tables...');
        connection = await oracledb.getConnection(adminConfig);
        console.log('✅ Connected.');

        // 1. Create Authors Table in UTPAL
        console.log('🔨 Creating NEWS_AUTHORS...');
        await connection.execute(`
      CREATE TABLE UTPAL.NEWS_AUTHORS (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(100) NOT NULL,
        role VARCHAR2(50) DEFAULT 'Editor',
        avatar_url VARCHAR2(255),
        bio VARCHAR2(1000)
      )
    `);

        // 2. Create Articles Table in UTPAL
        console.log('🔨 Creating NEWS_ARTICLES...');
        await connection.execute(`
      CREATE TABLE UTPAL.NEWS_ARTICLES (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        slug VARCHAR2(200) NOT NULL UNIQUE,
        title VARCHAR2(300) NOT NULL,
        subtitle VARCHAR2(500),
        content CLOB NOT NULL,
        category VARCHAR2(50) NOT NULL,
        image_url VARCHAR2(500),
        author_id NUMBER,
        published_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_utpal_author_new FOREIGN KEY (author_id) REFERENCES UTPAL.NEWS_AUTHORS(id)
      )
    `);

        // 3. Insert fresh sample data
        console.log('👤 Inserting Author...');
        await connection.execute(`INSERT INTO UTPAL.NEWS_AUTHORS (name, role) VALUES ('Utpal', 'Editor-in-Chief')`);

        console.log('📰 Inserting Articles...');
        const articles = [
            ['spacex-starship', 'SpaceX Starship Reaches Orbit', 'A major milestone for the future of Mars exploration.', 'Space', 'https://images.unsplash.com/photo-1517976487492-5750f3195933', 1],
            ['ai-future', 'The Future of AI in 2026', 'How neural networks are changing daily life.', 'Tech', 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485', 1],
            ['global-economy', 'Global Economy Forecast', 'Stable growth predicted for the next decade.', 'Business', 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e', 1]
        ];

        for (const art of articles) {
            await connection.execute(
                `INSERT INTO UTPAL.NEWS_ARTICLES (slug, title, content, category, image_url, author_id) 
         VALUES (:1, :2, :3, :4, :5, :6)`,
                art
            );
        }

        await connection.commit();
        console.log('✨ SUCCESS! UTPAL schema is ready for the website.');

    } catch (err) {
        console.error('❌ Failed:', err);
    } finally {
        if (connection) await connection.close();
    }
}

recreateWebsiteTables();
