require('dotenv').config({ path: '.env.local' });
const oracledb = require('oracledb');
const path = require('path');

try {
    oracledb.initOracleClient({ configDir: path.resolve(process.cwd(), 'oracle_wallet') });
} catch (err) { }

const dbConfig = {
    user: process.env.ORACLE_DB_USER || 'ADMIN',
    password: process.env.ORACLE_DB_PASSWORD,
    connectString: 'm2_high'
};

async function setupDatabase() {
    let connection;
    try {
        connection = await oracledb.getConnection(dbConfig);
        try { await connection.execute(`DROP TABLE NEWS_ARTICLES CASCADE CONSTRAINTS`); } catch (e) { }
        try { await connection.execute(`DROP TABLE NEWS_AUTHORS CASCADE CONSTRAINTS`); } catch (e) { }

        await connection.execute(`
      CREATE TABLE NEWS_AUTHORS (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(100) NOT NULL,
        role VARCHAR2(50) DEFAULT 'Editor',
        avatar_url VARCHAR2(255),
        bio VARCHAR2(1000)
      )
    `);

        await connection.execute(`
      CREATE TABLE NEWS_ARTICLES (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        slug VARCHAR2(200) NOT NULL UNIQUE,
        title VARCHAR2(300) NOT NULL,
        subtitle VARCHAR2(500),
        content CLOB NOT NULL,
        category VARCHAR2(50) NOT NULL,
        image_url VARCHAR2(500),
        image_caption VARCHAR2(300),
        author_id NUMBER,
        published_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        status VARCHAR2(20) DEFAULT 'PUBLISHED',
        views NUMBER DEFAULT 0,
        tags VARCHAR2(200),
        CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES NEWS_AUTHORS(id)
      )
    `);

        await connection.execute(
            `INSERT INTO NEWS_AUTHORS (name, role, avatar_url, bio) VALUES (:1, :2, :3, :4)`,
            ['Utpal', 'Editor-in-Chief', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Utpal', 'Space enthusiast and tech reporter.']
        );
        await connection.commit();

        const authorRes = await connection.execute(`SELECT id FROM NEWS_AUTHORS WHERE name = 'Utpal'`, [], { outFormat: oracledb.OUT_FORMAT_OBJECT });
        const authorId = authorRes.rows[0].ID || authorRes.rows[0].id;

        const articles = [
            {
                slug: 'spacex-starship-launch',
                title: 'SpaceX Starship Successfully Reaches Orbit',
                subtitle: 'A historic milestone for space exploration as the massive rocket achieves orbit.',
                content: 'SpaceX has successfully launched its massive Starship rocket, marking a major step forward in the company\'s goal of reaching Mars...',
                category: 'Space',
                image: 'https://images.unsplash.com/photo-1517976487492-5750f3195933?auto=format&fit=crop&q=80',
                tags: 'SpaceX,Mars,Rocket'
            }
        ];

        for (const art of articles) {
            await connection.execute(
                `INSERT INTO NEWS_ARTICLES (slug, title, subtitle, content, category, image_url, author_id, tags) 
         VALUES (:1, :2, :3, :4, :5, :6, :7, :8)`,
                [art.slug, art.title, art.subtitle, art.content, art.category, art.image, authorId, art.tags]
            );
        }
        await connection.commit();
        console.log('✅ Database Setup Complete!');
    } catch (err) {
        console.error('❌ Setup Failed:', err);
    } finally {
        if (connection) await connection.close();
    }
}

setupDatabase();
